apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gymmax-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gymmax
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80
