apiVersion: apps/v1
kind: Deployment
metadata:
  name: gymmax
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gymmax
  template:
    metadata:
      labels:
        app: gymmax
    spec:
      containers:
      - name: gymmax
        image: mylandmax/kubwebtest:v2
        ports:
        - containerPort: 80
        resources:
          requests:
          # 1000m is 1 core. 1 node heeft 1 core.
          # 5 pods met 250m kan dan ook niet. Pod wordt niet aangemaakt en blijft pending.
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: gymmax-service
  labels:
    app: gymmax-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gymmax
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gymmax-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gymmax
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80
